export const enum AccountActionNames {
    SET_PASSWORD = "ACC_SET_PASSWORD",
    RETRIEVE_PASSOWRD = "ACC_RETRIEVE_PASSOWRD",
    SET_AUTHORIZED = "ACC_SET_AUTHORIZED",
    RETRIEVE_AUTHORIZED = "ACC_RETRIEVE_AUTHORIZED",
    RESET = "ACC_RESET",
}
