export const enum AccountTypes {
    SET_ACCOUNT_PASSWORD = "SET_ACCOUNT_PASSWORD",
    SET_LOGGED_IN = "SET_LOGGED_IN",
    LOG_IN = "LOG_IN",
    LOG_OUT = "LOG_OUT",
    LOG_IN_FAILURE = "LOG_IN_FAILURE",
    RESET_ACCOUNT = "RESET_ACCOUNT",
    IS_RESETED_ACCOUNT = "IS_RESETED_ACCOUNT",
    INIT_ACCOUNT = "INIT_ACCOUNT",
}
