export const enum CryptoTypes {
    INIT_CRYPTO = "INIT_CRYPTO",
    SET_SECRET = "SET_SECRET",
    GENERATE_SECRET = "GENERATE_SECRET",
    RESET_CRYPTO = "RESET_CRYPTO",
    REMOVE_SECRET = "REMOVE_SECRET",
    SAVE_SECRET = "SAVE_SECRET",
    SAVE_SECRET_SUCCESS = "SAVE_SECRET_SUCCESS",
    SAVE_SECRET_FAILURE = "SAVE_SECRET_FAILURE",
}
