name: Lint
on:
  push:
    branches: [main, develop]
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
      - 'releases/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
